name: PlatformIO Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build firmware
        uses: n-vr/setup-platformio-action@v1

      - name: PlatformIO build
        run: pio run
